### ISSUE TITLE
Accessing an SQLCatalog accesses all tables in database? 

### ISSUE THREAD

**Issue by mjmare** [intake/intake-sql#16]
I'm trying out SQLCatalog on my database that contains a lot of tables (~270). 
```
  mydb:
    description: My database
    driver: sql_cat
    args:
      uri: "mysql+mysqlconnector://......."
    metadata: {}
```
When I access the catalog with 
```
cat = intake.open_catalog('mycat.yml')
cat.mydb
```
it takes ages (up to 5 mins) for the last call to return. So it seems it introspects all tables.
Calling it again is no faster, so it does not cache its data. 
Even accessing 1 table from the cat is slow. 

Am I doing something wrong?

PS accessing individual tables with the sql driver seems to work fine.
