### ISSUE TITLE
where_values not providable as lists

### ISSUE THREAD

**Issue by paularmand** [intake/intake-sql#4]
The catalog below contains user parameters for ```where_string``` and ```where_list```. The ```where_string``` works correctly in the ```where_values``` arg, but I can't get ```where_list``` to function correctly in the ```where_values```, since ```where_values``` already is a list. I tried to use 
```
where_values: {{ where_list }}     
```
but the template engine complains about this one (unhashable dict). I'm unsure whether I've missed something. If this should be fixed, please advice on a direction, and I'll try to make a PR.

catalog.yaml
```
metadata:
  version: 1
sources:
  mh_data_anonymization:
    description: "data set used for pseudonymization in the data team"
    direct_access: 'allow'
    driver: sql_manual
    args:
      uri: "{{ param_uri }}"
      sql_expr: "SELECT {{ top }} * FROM {{table_name}}"
      where_values: ["{{ where_string }}"]
      # where_values: ["{{ where_list }}"]           # not functioning
    parameters: # User defined parameters
      param_uri:
        description: "database uri in sqlalchemy style"
        type: str
        default: env(TEST_MSSQL_URI)
      table_name:
        description: "name of the table"
        type: str
        default: "IdentityProfilingMap"
      top:
        description: "number of results to return, e.g. top='TOP 200'"
        type: str
        default: "TOP 10"
      where_string:
        description: "list of string, or list of tuples"        
        type: str
        default: "WHERE Id<126040"
      where_list:
        description: "list of string, or list of tuples"        
        type: list
        default: ["WHERE Id<126040"]
```

**Comment by martindurant** [comment]
You are right, that Intake does not descent into structures like lists to apply parameters. Maybe it should, and it would not be too complex to implement (any interest in doing this?).

For your situation, though, I'm not sure it is necessary: you no longer have to use templating in order for a given argument to be over-ridable by the user. This is true since https://github.com/intake/intake/pull/287 .
```
sources:
  mh_data_anonymization:
    description: "data set used for pseudonymization in the data team"
    direct_access: 'allow'
    driver: sql_manual
    args:
      uri: "{{ param_uri }}"
      sql_expr: "SELECT {{ top }} * FROM {{table_name}}"
      where_values: ["WHERE Id<126040"]
    parameters:
      where_values:
        description: "This should be a list of string"        
        type: list
```
Here we give the default directly as the argument. The user can override with `cat.mh_data_anonymization(where_values=[...])`. The *same* key is in the parameters block, which means that the value passed by the user will be coerced to a list and the existence of the block and the description is meant to inform the user; it is optional, and override is possible without it.
